import type { CalendarEvent } from "./types";

function isoForThisWeek(dayOffset: number, hh: number, mm: number): string {
  const now = new Date();
  const d = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + dayOffset, hh, mm, 0),
  );
  return d.toISOString();
}

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: "m1",
    event_type_id: null,
    title: "US CPI YoY",
    release_at: isoForThisWeek(0, 13, 30),
    impact: "high",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 3.1,
    previous: 3.2,
    event_type_slug: "us-cpi-yoy",
  },
  {
    id: "m2",
    event_type_id: null,
    title: "US Core CPI YoY",
    release_at: isoForThisWeek(0, 13, 30),
    impact: "high",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 3.3,
    previous: 3.3,
    event_type_slug: "us-core-cpi-yoy",
  },
  {
    id: "m3",
    event_type_id: null,
    title: "ECB Interest Rate Decision",
    release_at: isoForThisWeek(1, 12, 45),
    impact: "high",
    currency: "EUR",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 3.25,
    previous: 3.25,
    event_type_slug: "ecb-rate-decision",
  },
  {
    id: "m4",
    event_type_id: null,
    title: "US Retail Sales MoM",
    release_at: isoForThisWeek(1, 13, 30),
    impact: "medium",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 0.3,
    previous: 0.4,
    event_type_slug: "us-retail-sales-mom",
  },
  {
    id: "m5",
    event_type_id: null,
    title: "US Initial Jobless Claims",
    release_at: isoForThisWeek(2, 13, 30),
    impact: "medium",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 220,
    previous: 218,
    event_type_slug: "us-jobless-claims",
  },
  {
    id: "m6",
    event_type_id: null,
    title: "BoJ Press Conference",
    release_at: isoForThisWeek(2, 6, 30),
    impact: "high",
    currency: "JPY",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: null,
    previous: null,
    event_type_slug: "boj-press-conference",
  },
  {
    id: "m7",
    event_type_id: null,
    title: "UK GDP QoQ",
    release_at: isoForThisWeek(3, 6, 0),
    impact: "medium",
    currency: "GBP",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 0.2,
    previous: 0.1,
    event_type_slug: "uk-gdp-qoq",
  },
  {
    id: "m8",
    event_type_id: null,
    title: "US Non-Farm Payrolls",
    release_at: isoForThisWeek(4, 13, 30),
    impact: "high",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 180,
    previous: 175,
    event_type_slug: "us-nfp",
  },
  {
    id: "m9",
    event_type_id: null,
    title: "US Unemployment Rate",
    release_at: isoForThisWeek(4, 13, 30),
    impact: "high",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: 4.1,
    previous: 4.1,
    event_type_slug: "us-unemployment-rate",
  },
  {
    id: "m10",
    event_type_id: null,
    title: "FOMC Member Powell Speech",
    release_at: isoForThisWeek(4, 18, 0),
    impact: "high",
    currency: "USD",
    source: "mock",
    source_ref: null,
    actual: null,
    forecast: null,
    previous: null,
    event_type_slug: "fomc-powell-speech",
  },
];
